server:
  port: 21203
security:
  basic:
    enabled: false   # 启用安全认证处理
  user:
    name: gauge     # 用户名
    password: sparksubmit666  # 密码

#eureka:
#  client: # 客户端进行Eureka注册的配置
#    service-url:
#      defaultZone: http://gauge:sparksubmit666@eureka-7001.com:7001/eureka,http://gauge:sparksubmit666@eureka-7002.com:7002/eureka,http://gauge:sparksubmit666@eureka-7003.com:7003/eureka
#  instance:
#    lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
#    lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）
#    instance-id: coolapi-8001.com  # 在信息列表时显示主机名称
#    prefer-ip-address: true     # 访问的路径变为IP地址

info:
  app.name: gauge-doc-docker
  company.name: www.gauge-doc-docker.com
  build.artifactId: $project.artifactId$
  build.version: $project.verson$


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml    # mybatis配置文件所在路径
  #type-aliases-package: com.gauge.docdocker.vm      # 定义所有操作类的别名所在包
  type-aliases-package: com.gauge.viewmodel      # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mybatis/mapper/**/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    driver-class-name: org.gjt.mm.mysql.Driver      # 配置MySQL的驱动程序类
    url: jdbc:mysql://192.168.1.7:3306/base_api           # 数据库连接地址
    username: root                                  # 数据库用户名
    password: sparksubmit666                            # 数据库连接密码
    dbcp2:                                          # 进行数据库连接池的配置
      min-idle: 5                                   # 数据库连接池的最小维持连接数    
      initial-size: 5                               # 初始化提供的连接数
      max-total: 5                                  # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间
  application:
    name: docdocker-provider-jenkinsjob
